# Generated by Django 4.2 on 2023-04-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.IntegerField(unique=True)),
                ('definition_id', models.TextField(unique=True)),
                ('scans', models.JSONField(blank=True, default=list)),
                ('url', models.URLField()),
                ('path', models.URLField()),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH'), ('OPTIONS', 'OPTIONS'), ('HEAD', 'HEAD')], default='INVALID', max_length=10)),
            ],
        ),
    ]
