# Generated by Django 4.2 on 2023-04-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_finding_definition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='target_id',
            field=models.TextField(),
        ),
    ]
